### ISSUE TITLE
Controller error

### ISSUE THREAD

**Issue by infabo** [tzyganu/moduleCreator#14] opened 2014-04-16 13:53 UTC
Hi!

I just check out this extension and I just simply cant get the backend of my created module to work.
I can see the menu, but when I try to access one of the menu itemse.g.

http://mylocal.dev/index.php/admin/eventticket_cultureevent/index/key/8486251f91e84da4ddd9d37587173249/

Ii just get redirected to the frontend with an 404. Same goes for any other Entity created by the ultimate module creator.

Is this a general issue or is it just no comptabile with 1.8.1?

Thanks
Ingo

**Comment by tzyganu** [comment] 2014-04-16 14:08
@infabo Please send me by e-mail the generated XML file for the module. You will find it in `var/modulecrator/package`. It has the same name as the module you created. `Namespace_Module.xml`. This way I can reproduce this on my side and see what's wrong with it.  

In addition you can try this: 

Clear the cache, 
Disable the compiler. 
Make sure that your module name does not have an uppercase letter in inside it. So `Modulename` is OK, `ModuleName` is not OK. If this is the case for you then I know about this issue. It doesn't work on UNIX servers because of of the case sensitive folder names. This will be fixed in the upcomming version.

**Comment by infabo** [comment] 2014-04-16 14:24
@tzyganu 

Thanks for your quick response!
OK, then my module name is the problem here. It is EventTicket. Can I fix that manually, because CamelCase is our rule here....

**Comment by tzyganu** [comment] 2014-04-16 14:31
@infabo .
You have 2 options. Either try the new version of the module creator that is not yet released https://github.com/tzyganu/UMC1.9 and recreate your module. That new version has this bug fixed already. 

The second option is to do it manually.  
Inside a folder `controllers/Adminhtml` of your module there should be an other folder called `EventTicket`. Rename that folder to `Eventticket` and all the classes inside that to match the path they are in and it should work.

**Comment by infabo** [comment] 2014-04-16 14:46
@tzyganu

I would like to try the new version, but it apparently does not have a modman file yet.

**Comment by tzyganu** [comment] 2014-04-25 11:26
@infabo The new version has been released. and it has a modman file.  https://github.com/tzyganu/UMC1.9/.

I will close this issue because this is fixed in the new version and the support for this version will end soon.

**Closed as completed by tzyganu** 2014-04-25 11:26 UTC

**Comment by infabo** [comment] 2014-04-25 12:11
Thank you!
UMC1.9 is awesome and a BIG step forward. Keep up the great work. I'll try to give further feedback on UMC1.9 on the repo over there, cause I already discovered some issues with it.

**Comment by tzyganu** [comment] 2014-04-25 12:21
@infabo Sure, please report anything you find. I can use all the help I can get.
