### ISSUE TITLE
Save form variables in session

### ISSUE THREAD

**Issue by alexpunct** [tzyganu/moduleCreator#13] opened 2013-10-24 10:47 UTC
When creating a new module and trying to save, store the variables in the session and fill them if we got an error. Now you are forced to start from scratch if you got a back-end error (ex: the module could not write the files).

**Comment by alexpunct** [comment] 2013-10-24 10:50
Even though I had an error, it generated the files apparently

**Comment by tzyganu** [comment] 2013-10-24 10:57
@alexpunct  I agree. This should be done, but can you tell me what the error was and how can I reproduce it?

**Comment by alexpunct** [comment] 2013-10-24 11:13
It was something with the Writer model, I closed the window, it could be that I didn't have the var folder created

**Comment by tzyganu** [comment] 2014-04-25 11:29
@alexpunct  I was not able to reproduce this issue.  
I will close this but not because I wasn't able to reproduce it. 
The support for this version comes to an end.  
In the new version that can be found here https://github.com/tzyganu/UMC1.9/  this issue should not appear. The save method of the module was modified to be done via an AJAX call. any error that appears in the save process will show a message at the top of the page and will keep you in the same screen.

**Closed as completed by tzyganu** 2014-04-25 11:29 UTC
Labels: bug
